use std::env;
use std::fs;
use std::path::PathBuf;

fn main() {
    let manifest = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let videos = manifest.join("assets").join("videos");
    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());

    // 扫描所有 webm 素材
    let mut entries: Vec<PathBuf> = fs::read_dir(&videos)
        .expect("assets/videos 目录缺失")
        .filter_map(|e| e.ok())
        .map(|e| e.path())
        .filter(|p| p.extension().map_or(false, |e| e == "webm"))
        .collect();
    entries.sort();

    if entries.is_empty() {
        panic!("assets/videos 下没有 webm 素材");
    }

    // 拼接成单个 pak + 生成索引
    let mut pak: Vec<u8> = Vec::new();
    let mut table: Vec<(String, usize, usize)> = Vec::new();
    for p in &entries {
        let name = p.file_stem().unwrap().to_str().unwrap().to_string();
        let data = fs::read(p).unwrap();
        let start = pak.len();
        pak.extend_from_slice(&data);
        table.push((name, start, data.len()));
    }
    fs::write(out_dir.join("assets.pak"), &pak).unwrap();

    // 生成索引 rust 源码
    let mut code = String::new();
    code.push_str("// auto-generated by build.rs\n");
    code.push_str("pub static ASSET_PAK: &[u8] = include_bytes!(concat!(env!(\"OUT_DIR\"), \"/assets.pak\"));\n");
    code.push_str("pub static ANIMS: &[(&str, usize, usize)] = &[\n");
    for (name, start, len) in &table {
        let escaped = name.replace('\\', "\\\\").replace('"', "\\\"");
        code.push_str(&format!("    (\"{}\", {}, {}),\n", escaped, start, len));
    }
    code.push_str("];\n");
    fs::write(out_dir.join("assets_gen.rs"), code).unwrap();

    println!("cargo:rerun-if-changed=assets/videos");
    println!("cargo:rustc-link-search=native={}", manifest.join("vendor_libvpx/x64/Release").display());
}
